### ISSUE TITLE
Code for computing the `Weighted feedback arc` and `Weighted reversing join` metrics

### ISSUE THREAD

**Issue by AndreaGuarracino** [anialisiecka/ALIBI#2]
To be super sure to compute the same values, could you please share the code you've used to compute the following metrics?

- Weighted feedback arc (WFA) – the sum of weights of all feedback arcs, i.e. backward pointing edges
- Weighted reversing join (WRJ) – the sum of weights of all reversing joins, i.e. edges joining two in- or two out-sides.

**Comment by anialisiecka** [comment]
[Here](https://github.com/anialisiecka/ALIBI/tree/master/metrics) is the code for computing the **weighted feedback arc** and **weighted reversing join** metrics.

**Comment by AndreaGuarracino** [comment]
Very kind, thank you.
